name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"

jobs:
  build:
    # Pinned to ZMK v0.2 release to avoid breaking changes
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
